# Milestone 2 · Data Cleaning and Preparation

## 2.1. Importing Libraries

In [1]:
import pandas as pd

## 2.2. Loading The Datasets

In [2]:
# Loading all dataset
orders = pd.read_csv("../data/raw/orders.csv")
order_items = pd.read_csv("../data/raw/order_items.csv")
customers = pd.read_csv("../data/raw/customers.csv")
products = pd.read_csv("../data/raw/products.csv")
stores = pd.read_csv("../data/raw/stores.csv")
county_population = pd.read_csv("../data/raw/county_population_2019_knbs.csv")

In [3]:
orders.head()

,order_id,store_id,order_datetime,customer_id,channel,payment_method,order_date,item_units,gross_amount_kes,discount_amount_kes,net_amount_kes,promotion_applied
0,O0000001,S002,2024-01-01 08:06:40,C003000,In-store,M-Pesa,2024-01-01,4,1031.00,0.00,1031.00,False
1,O0000002,S002,2024-01-01 08:08:38,C003410,In-store,M-Pesa,2024-01-01,1,178.38,26.76,151.62,True
2,O0000003,S004,2024-01-01 08:15:46,C007400,In-store,M-Pesa,2024-01-01,3,1173.67,42.41,1131.26,True
3,O0000004,S004,2024-01-01 08:19:06,NaN,In-store,M-Pesa,2024-01-01,7,1150.12,0.00,1150.12,False
4,O0000005,S002,2024-01-01 08:23:39,C003652,In-store,M-Pesa,2024-01-01,5,825.89,0.00,825.89,False

In [4]:
order_items.head()

,line_id,order_id,product_id,quantity,unit_price_kes,unit_cost_kes,discount_pct,line_gross_kes,line_discount_kes,line_net_kes
0,L00093104,O0035825,P0004,1,195.42,140.89,0,195.42,0.0,195.42
1,L00211065,O0081115,P0009,2,152.96,106.98,0,305.92,0.0,305.92
2,L00180061,O0069133,P0047,1,279.47,178.05,0,279.47,0.0,279.47
3,L00241120,O0092580,P0028,2,172.03,129.22,0,344.06,0.0,344.06
4,L00637964,O0244780,P0078,1,473.92,346.85,0,473.92,0.0,473.92

In [5]:
customers.head()

,customer_id,registration_date,home_county,preferred_store_id,age_band,acquisition_channel
0,C000001,2025-01-18,Nairobi,S001,35-44,Social media
1,C000002,2026-08-31,Nairobi,S001,45-54,In-store signup
2,C000003,2026-02-18,Nairobi,S001,45-54,Social media
3,C000004,2025-09-05,Nairobi,S001,18-24,Website
4,C000005,2026-03-21,Nairobi,S001,18-24,Referral

In [6]:
products.head()

,product_id,category,product_name,base_list_price_kes,base_unit_cost_kes,is_perishable,is_active
0,P0001,Staples,Maize Flour 2kg,168,139.07,False,True
1,P0002,Staples,Rice 1kg,215,177.07,False,True
2,P0003,Staples,Rice 2kg,420,279.62,False,True
3,P0004,Staples,Wheat Flour 2kg,188,138.24,False,True
4,P0005,Staples,Sugar 1kg,175,126.90,False,True

In [7]:
county_population.head()

,county,census_year,population_2019,source,source_url
0,Nairobi,2019,4397073,KNBS 2019 Kenya Population and Housing Census,https://www.knbs.or.ke/reports/kenya-census-2019/
1,Kiambu,2019,2417735,KNBS 2019 Kenya Population and Housing Census,https://www.knbs.or.ke/reports/kenya-census-2019/
2,Nakuru,2019,2162202,KNBS 2019 Kenya Population and Housing Census,https://www.knbs.or.ke/reports/kenya-census-2019/
3,Mombasa,2019,1208333,KNBS 2019 Kenya Population and Housing Census,https://www.knbs.or.ke/reports/kenya-census-2019/
4,Kisumu,2019,1155574,KNBS 2019 Kenya Population and Housing Census,https://www.knbs.or.ke/reports/kenya-census-2019/

In [8]:
stores.head()

,store_id,store_name,county,town,opening_date,store_format
0,S001,Mwangaza MiniMart - Ngara,Nairobi,Ngara,2024-01-01,Neighbourhood
1,S002,Mwangaza MiniMart - South B,Nairobi,South B,2024-01-01,Neighbourhood
2,S003,Mwangaza MiniMart - Thika,Kiambu,Thika,2024-01-01,Neighbourhood
3,S004,Mwangaza MiniMart - Nakuru,Nakuru,Nakuru,2024-01-01,Neighbourhood
4,S005,Mwangaza MiniMart - Nyali,Mombasa,Nyali,2024-01-01,Neighbourhood

## 2.3. Exploring Datasets

In [9]:
# Verifying Datasets
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Stores:", stores.shape)
print("County Population:", county_population.shape)

Orders: (316277, 12)
Order Items: (824761, 10)
Customers: (19000, 6)
Products: (99, 7)
Stores: (10, 6)
County Population: (8, 5)

In [10]:
# Basic Checks
def basic_checks(data, name):
    print("\n" + "=" * 35)
    print(f"DATASET: {name.upper()}")
    print("=" * 35)
    print("="*35, "SHAPE", "="*35)
    print(data.shape)
    print("="*35, "INFO", "="*35)
    data.info()
    print("="*35, "COLUMNS", "="*35)
    print(data.columns.to_list())
    print("="*35, "DATA TYPES", "="*35)
    print(data.dtypes)
    print("="*35, "NULLS", "="*35)
    print(data.isnull().sum())
    print("="*35, "MISSING VALUES PERCENTAGE", "="*35)
    print((data.isnull().sum()/len(data))*100)
    print("="*35, "DUPLICATES", "="*35)
    print(data.duplicated().sum())
    print("="*35, "UNIQUE VALUE COUNTS", "="*35)
    print(data.nunique())
    print("="*35, "NUMERICAL STATS", "="*35)
    print(data.describe().T)

In [11]:
basic_checks(orders, "Orders")
basic_checks(order_items, "Order Items")
basic_checks(customers, "Customers")
basic_checks(products, "Products")
basic_checks(stores, "Stores")
basic_checks(county_population, "County Population")

===================================
DATASET: ORDERS
===================================
=================================== SHAPE ===================================
(316277, 12)
=================================== INFO ===================================
<class 'pandas.DataFrame'>
RangeIndex: 316277 entries, 0 to 316276
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             316277 non-null  str
 1   store_id             316277 non-null  str
 2   order_datetime       316277 non-null  str
 3   customer_id          246424 non-null  str
 4   channel              316277 non-null  str
 5   payment_method       315486 non-null  str
 6   order_date           316277 non-null  str
 7   item_units           316277 non-null  int64
 8   gross_amount_kes     316277 non-null  float64
 9   discount_amount_kes  316277 non-null  float64
 10  net_amount_kes       316277 non-null  float64
 11  promotion_applied    316277 non-null  bool
dtypes: bool(1), float64(3), int64(1), str(7)
memory usage: 26.8 MB
=================================== COLUMNS ===================================
['order_id', 'store_id', 'order_datetime', 'customer_id', 'channel', 'payment_method', 'order_date', 'item_units', 'gross_amount_kes', 'discount_amount_kes', 'net_amount_kes', 'promotion_applied']
=================================== DATA TYPES ===================================
order_id                   str
store_id                   str
order_datetime             str
customer_id                str
channel                    str
payment_method             str
order_date                 str
item_units               int64
gross_amount_kes       float64
discount_amount_kes    float64
net_amount_kes         float64
promotion_applied         bool
dtype: object
=================================== NULLS ===================================
order_id                   0
store_id                   0
order_datetime             0
customer_id            69853
channel                    0
payment_method           791
order_date                 0
item_units                 0
gross_amount_kes           0
discount_amount_kes        0
net_amount_kes             0
promotion_applied          0
dtype: int64
=================================== MISSING VALUES PERCENTAGE ===================================
order_id                0.000000
store_id                0.000000
order_datetime          0.000000
customer_id            22.086020
channel                 0.000000
payment_method          0.250097
order_date              0.000000
item_units              0.000000
gross_amount_kes        0.000000
discount_amount_kes     0.000000
net_amount_kes          0.000000
promotion_applied       0.000000
dtype: float64
=================================== DUPLICATES ===================================
0
=================================== UNIQUE VALUE COUNTS ===================================
order_id               316277
store_id                   10
order_datetime         315032
customer_id             16070
channel                     3
payment_method              5
order_date               1004
item_units                 19
gross_amount_kes       150110
discount_amount_kes     12463
net_amount_kes         149620
promotion_applied           2
dtype: int64
=================================== NUMERICAL STATS ===================================
                        count        mean         std    min     25%     50%  \
item_units           316277.0    3.880254    2.355590   1.00    2.00    3.00
gross_amount_kes     316277.0  812.310041  589.493001  43.41  369.51  673.37
discount_amount_kes  316277.0    9.307299   23.137910   0.00    0.00    0.00
net_amount_kes       316277.0  803.002742  583.235122  37.76  365.03  665.31

                         75%      max
item_units              5.00    19.00
gross_amount_kes     1110.51  5883.13
discount_amount_kes     6.92   572.99
net_amount_kes       1097.80  5883.13

===================================
DATASET: ORDER ITEMS
===================================
=================================== SHAPE ===================================
(824761, 10)
=================================== INFO ===================================
<class 'pandas.DataFrame'>
RangeIndex: 824761 entries, 0 to 824760
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   line_id            824761 non-null  str
 1   order_id           824761 non-null  str
 2   product_id         824761 non-null  str
 3   quantity           824761 non-null  int64
 4   unit_price_kes     823113 non-null  float64
 5   unit_cost_kes      824761 non-null  float64
 6   discount_pct       824761 non-null  int64
 7   line_gross_kes     824761 non-null  float64
 8   line_discount_kes  824761 non-null  float64
 9   line_net_kes       824761 non-null  float64
dtypes: float64(5), int64(2), str(3)
memory usage: 62.9 MB
=================================== COLUMNS ===================================
['line_id', 'order_id', 'product_id', 'quantity', 'unit_price_kes', 'unit_cost_kes', 'discount_pct', 'line_gross_kes', 'line_discount_kes', 'line_net_kes']
=================================== DATA TYPES ===================================
line_id                  str
order_id                 str
product_id               str
quantity               int64
unit_price_kes       float64
unit_cost_kes        float64
discount_pct           int64
line_gross_kes       float64
line_discount_kes    float64
line_net_kes         float64
dtype: object
=================================== NULLS ===================================
line_id                 0
order_id                0
product_id              0
quantity                0
unit_price_kes       1648
unit_cost_kes           0
discount_pct            0
line_gross_kes          0
line_discount_kes       0
line_net_kes            0
dtype: int64
=================================== MISSING VALUES PERCENTAGE ===================================
line_id              0.000000
order_id             0.000000
product_id           0.000000
quantity             0.000000
unit_price_kes       0.199815
unit_cost_kes        0.000000
discount_pct         0.000000
line_gross_kes       0.000000
line_discount_kes    0.000000
line_net_kes         0.000000
dtype: float64
=================================== DUPLICATES ===================================
989
=================================== UNIQUE VALUE COUNTS ===================================
line_id              823772
order_id             316277
product_id               99
quantity                  8
unit_price_kes        53933
unit_cost_kes          3049
discount_pct              4
line_gross_kes        94471
line_discount_kes     11412
line_net_kes          96527
dtype: int64
=================================== NUMERICAL STATS ===================================
                      count        mean         std    min     25%     50%  \
quantity           824761.0    1.525489    1.844687   1.00    1.00    1.00
unit_price_kes     823113.0  209.262650  117.175060  42.72  123.39  180.49
unit_cost_kes      824761.0  153.851047   87.096267  36.36   91.38  130.81
discount_pct       824761.0    1.145368    3.289127   0.00    0.00    0.00
line_gross_kes     824761.0  311.873433  261.639509  42.72  149.88  227.80
line_discount_kes  824761.0    3.573445   13.700374   0.00    0.00    0.00
line_net_kes       824761.0  308.299988  259.010754  36.93  147.56  224.97

                      75%      max
quantity             2.00    99.00
unit_price_kes     269.45   620.87
unit_cost_kes      197.05   429.37
discount_pct         0.00    15.00
line_gross_kes     385.28  3023.70
line_discount_kes    0.00   453.56
line_net_kes       381.41  3006.00

===================================
DATASET: CUSTOMERS
===================================
=================================== SHAPE ===================================
(19000, 6)
=================================== INFO ===================================
<class 'pandas.DataFrame'>
RangeIndex: 19000 entries, 0 to 18999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          19000 non-null  str
 1   registration_date    19000 non-null  str
 2   home_county          19000 non-null  str
 3   preferred_store_id   19000 non-null  str
 4   age_band             18848 non-null  str
 5   acquisition_channel  19000 non-null  str
dtypes: str(6)
memory usage: 890.8 KB
=================================== COLUMNS ===================================
['customer_id', 'registration_date', 'home_county', 'preferred_store_id', 'age_band', 'acquisition_channel']
=================================== DATA TYPES ===================================
customer_id            str
registration_date      str
home_county            str
preferred_store_id     str
age_band               str
acquisition_channel    str
dtype: object
=================================== NULLS ===================================
customer_id              0
registration_date        0
home_county              0
preferred_store_id       0
age_band               152
acquisition_channel      0
dtype: int64
=================================== MISSING VALUES PERCENTAGE ===================================
customer_id            0.0
registration_date      0.0
home_county            0.0
preferred_store_id     0.0
age_band               0.8
acquisition_channel    0.0
dtype: float64
=================================== DUPLICATES ===================================
0
=================================== UNIQUE VALUE COUNTS ===================================
customer_id            19000
registration_date       1073
home_county                8
preferred_store_id        10
age_band                   5
acquisition_channel        4
dtype: int64
=================================== NUMERICAL STATS ===================================
                     count unique              top  freq
customer_id          19000  19000          C000001     1
registration_date    19000   1073       2026-07-30    49
home_county          19000      8          Nairobi  3800
preferred_store_id   19000     10             S001  1900
age_band             18848      5            25-34  6185
acquisition_channel  19000      4  In-store signup  9908

===================================
DATASET: PRODUCTS
===================================
=================================== SHAPE ===================================
(99, 7)
=================================== INFO ===================================
<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           99 non-null     str
 1   category             99 non-null     str
 2   product_name         99 non-null     str
 3   base_list_price_kes  99 non-null     int64
 4   base_unit_cost_kes   99 non-null     float64
 5   is_perishable        99 non-null     bool
 6   is_active            99 non-null     bool
dtypes: bool(2), float64(1), int64(1), str(3)
memory usage: 4.2 KB
=================================== COLUMNS ===================================
['product_id', 'category', 'product_name', 'base_list_price_kes', 'base_unit_cost_kes', 'is_perishable', 'is_active']
=================================== DATA TYPES ===================================
product_id                 str
category                   str
product_name               str
base_list_price_kes      int64
base_unit_cost_kes     float64
is_perishable             bool
is_active                 bool
dtype: object
=================================== NULLS ===================================
product_id             0
category               0
product_name           0
base_list_price_kes    0
base_unit_cost_kes     0
is_perishable          0
is_active              0
dtype: int64
=================================== MISSING VALUES PERCENTAGE ===================================
product_id             0.0
category               0.0
product_name           0.0
base_list_price_kes    0.0
base_unit_cost_kes     0.0
is_perishable          0.0
is_active              0.0
dtype: float64
=================================== DUPLICATES ===================================
0
=================================== UNIQUE VALUE COUNTS ===================================
product_id             99
category               10
product_name           99
base_list_price_kes    56
base_unit_cost_kes     99
is_perishable           2
is_active               1
dtype: int64
=================================== NUMERICAL STATS ===================================
                     count        mean         std    min     25%     50%  \
base_list_price_kes   99.0  205.595960  119.112014  45.00  115.00  175.00
base_unit_cost_kes    99.0  153.053838   89.300013  36.36   84.25  126.21

                       75%    max
base_list_price_kes  295.0  520.0
base_unit_cost_kes   218.0  380.3

===================================
DATASET: STORES
===================================
=================================== SHAPE ===================================
(10, 6)
=================================== INFO ===================================
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      10 non-null     str
 1   store_name    10 non-null     str
 2   county        10 non-null     str
 3   town          10 non-null     str
 4   opening_date  10 non-null     str
 5   store_format  10 non-null     str
dtypes: str(6)
memory usage: 612.0 bytes
=================================== COLUMNS ===================================
['store_id', 'store_name', 'county', 'town', 'opening_date', 'store_format']
=================================== DATA TYPES ===================================
store_id        str
store_name      str
county          str
town            str
opening_date    str
store_format    str
dtype: object
=================================== NULLS ===================================
store_id        0
store_name      0
county          0
town            0
opening_date    0
store_format    0
dtype: int64
=================================== MISSING VALUES PERCENTAGE ===================================
store_id        0.0
store_name      0.0
county          0.0
town            0.0
opening_date    0.0
store_format    0.0
dtype: float64
=================================== DUPLICATES ===================================
0
=================================== UNIQUE VALUE COUNTS ===================================
store_id        10
store_name      10
county           8
town            10
opening_date     5
store_format     1
dtype: int64
=================================== NUMERICAL STATS ===================================
             count unique                        top freq
store_id        10     10                       S001    1
store_name      10     10  Mwangaza MiniMart - Ngara    1
county          10      8                    Nairobi    2
town            10     10                      Ngara    1
opening_date    10      5                 2024-01-01    6
store_format    10      1              Neighbourhood   10

===================================
DATASET: COUNTY POPULATION
===================================
=================================== SHAPE ===================================
(8, 5)
=================================== INFO ===================================
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   county           8 non-null      str
 1   census_year      8 non-null      int64
 2   population_2019  8 non-null      int64
 3   source           8 non-null      str
 4   source_url       8 non-null      str
dtypes: int64(2), str(3)
memory usage: 452.0 bytes
=================================== COLUMNS ===================================
['county', 'census_year', 'population_2019', 'source', 'source_url']
=================================== DATA TYPES ===================================
county               str
census_year        int64
population_2019    int64
source               str
source_url           str
dtype: object
=================================== NULLS ===================================
county             0
census_year        0
population_2019    0
source             0
source_url         0
dtype: int64
=================================== MISSING VALUES PERCENTAGE ===================================
county             0.0
census_year        0.0
population_2019    0.0
source             0.0
source_url         0.0
dtype: float64
=================================== DUPLICATES ===================================
0
=================================== UNIQUE VALUE COUNTS ===================================
county             8
census_year        1
population_2019    8
source             1
source_url         1
dtype: int64
=================================== NUMERICAL STATS ===================================
                 count         mean           std        min        25%  \
census_year        8.0     2019.000  0.000000e+00     2019.0     2019.0
population_2019    8.0  1880484.375  1.132943e+06  1117840.0  1161283.0

                       50%         75%        max
census_year         2019.0     2019.00     2019.0
population_2019  1315132.5  2226085.25  4397073.0

## 2.4. Fix Data Types

### 2.4.1. Converting Date Columns

In [12]:
# Convert date columns from strings to datetime

orders["order_date"] = pd.to_datetime(orders["order_date"])
orders["order_datetime"] = pd.to_datetime(orders["order_datetime"])

customers["registration_date"] = pd.to_datetime(customers["registration_date"])

stores["opening_date"] = pd.to_datetime(stores["opening_date"])

In [13]:
# Verify conversions
print(orders[["order_date", "order_datetime"]].dtypes)
print(customers["registration_date"].dtype)
print(stores["opening_date"].dtype)

order_date        datetime64[us]
order_datetime    datetime64[us]
dtype: object
datetime64[us]
datetime64[us]

## 2.5. Handling Missing Values

### 2.5.1. Handling Missing Values in Orders

In [14]:
# Count missing values before cleaning
payment_missing_before = orders["payment_method"].isnull().sum()

# Replace missing payment methods with Unknown
orders["payment_method"] = orders["payment_method"].fillna("Unknown")

# Check missing values after cleaning
payment_missing_after = orders["payment_method"].isnull().sum()

print("Before:", payment_missing_before)
print("After:", payment_missing_after)

Before: 791
After: 0

### 2.5.2. Handling Missing Values in Customers

In [15]:
# Missing age bands before cleaning
age_missing_before = customers["age_band"].isnull().sum()

# Fill missing age bands with Unknown
customers["age_band"] = customers["age_band"].fillna("Unknown")

# Missing age bands after cleaning
age_missing_after = customers["age_band"].isnull().sum()

print("Before:", age_missing_before)
print("After:", age_missing_after)

Before: 152
After: 0


### 2.5.3 Handling Missing Unit Prices

In [16]:
# Missing prices before cleaning
price_missing_before = order_items["unit_price_kes"].isnull().sum()

# Calculate missing unit prices
order_items["unit_price_kes"] = order_items["unit_price_kes"].fillna(
    (order_items["line_gross_kes"] / order_items["quantity"]).round(2)
)

# Missing prices after cleaning
price_missing_after = order_items["unit_price_kes"].isnull().sum()

print("Before:", price_missing_before)
print("After:", price_missing_after)

Before: 1648
After: 0

## 2.6 — Handling Duplicates

### 2.6.1 Removing Duplicate Records

In [17]:
# Count rows and duplicates before cleaning
rows_before = len(order_items)
duplicates_before = order_items.duplicated().sum()

# Remove duplicate records
order_items = order_items.drop_duplicates()

# Check results after cleaning
rows_after = len(order_items)
duplicates_after = order_items.duplicated().sum()

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Duplicates before:", duplicates_before)
print("Duplicates after:", duplicates_after)
print("Rows removed:", rows_before - rows_after)

Rows before: 824761
Rows after: 823772
Duplicates before: 989
Duplicates after: 0
Rows removed: 989

In [18]:
order_items["line_id"].duplicated().sum()

np.int64(0)

## 2.7. Handling Outliers

### 2.7.1 Identifying Quantity Outliers

In [19]:
# Check how frequently each quantity occurs
order_items["quantity"].value_counts().sort_index()

quantity
1     543379
2     193701
3      57522
4      20510
5       8248
49       138
75       159
99       115
Name: count, dtype: int64

In [20]:
# Identify unusually large quantities
outliers = order_items[order_items["quantity"] >= 49].copy()

print("Potential outliers:", len(outliers))

# Inspect a few records
outliers[["line_id", "quantity", "unit_price_kes", "line_gross_kes"]].head()

Potential outliers: 412

         line_id  quantity  unit_price_kes  line_gross_kes
5218   L00108815        99          331.62          331.62
6099   L00446788        99          554.76          554.76
9527   L00072606        99          147.37          147.37
9700   L00674474        75          153.76          307.52
10192  L00647749        49          155.96          467.88

In [21]:
# Calculate quantities using gross sales and unit prices
outliers["calculated_quantity"] = (
    outliers["line_gross_kes"] / outliers["unit_price_kes"]
).round()

# Compare recorded and calculated quantities
outliers[["quantity", "calculated_quantity"]].head(10)

       quantity  calculated_quantity
5218         99                  1.0
6099         99                  1.0
9527         99                  1.0
9700         75                  2.0
10192        49                  3.0
11452        99                  3.0
13732        49                  1.0
14961        99                  1.0
15109        75                  1.0
15163        99                  1.0

In [22]:
# Check the calculated quantities for all outliers
print(outliers["calculated_quantity"].value_counts().sort_index())

# Count calculated quantities outside the expected range
print("Invalid calculated quantities:",
      (~outliers["calculated_quantity"].between(1, 5)).sum())

calculated_quantity
1.0    280
2.0     88
3.0     29
4.0     10
5.0      5
Name: count, dtype: int64
Invalid calculated quantities: 0

### 2.7.2 Correcting Quantity Outliers

In [23]:
# Count outliers before correction
outliers_before = (order_items["quantity"] >= 49).sum()

# Replace incorrect quantities with calculated quantities
order_items.loc[outliers.index, "quantity"] = (
    outliers["calculated_quantity"].astype(int)
)

# Count outliers after correction
outliers_after = (order_items["quantity"] >= 49).sum()

print("Outliers before:", outliers_before)
print("Outliers after:", outliers_after)
print("Outliers corrected:", outliers_before - outliers_after)

Outliers before: 412
Outliers after: 0
Outliers corrected: 412

In [24]:
# Verify quantity distribution
order_items["quantity"].value_counts().sort_index()

quantity
1    543659
2    193789
3     57551
4     20520
5      8253
Name: count, dtype: int64

## 2.8. Feature Engineering

### 2.8.1 Creating Date Features

In [25]:
# Extract year and month from order_date
orders["year"] = orders["order_date"].dt.year
orders["month"] = orders["order_date"].dt.month

# Create year-month for monthly sales analysis
orders["year_month"] = orders["order_date"].dt.strftime("%Y-%m")

# Verify the new columns
orders[["order_date", "year", "month", "year_month"]].head()

  order_date  year  month year_month
0 2024-01-01  2024      1    2024-01
1 2024-01-01  2024      1    2024-01
2 2024-01-01  2024      1    2024-01
3 2024-01-01  2024      1    2024-01
4 2024-01-01  2024      1    2024-01

# 2.9 Final Data Validation

### 2.9.1 Checking Quantity Consistency

In [26]:
print("Total units in orders:", orders["item_units"].sum())

print("Total units in order items:", order_items["quantity"].sum())

Total units in orders: 1227235
Total units in order items: 1227235

### 2.9.2 Checking Quantity Consistency per Order

In [27]:
# Calculate total quantities for each order
items_per_order = order_items.groupby("order_id")["quantity"].sum()

# Compare against the orders table
units_match = orders["item_units"] == orders["order_id"].map(items_per_order)

# Display results
print("Orders matching:", units_match.sum())
print("Orders not matching:", (~units_match).sum())

Orders matching: 316277
Orders not matching: 0

### 2.9.3 Checking Revenue Consistency

In [28]:
# Calculate total revenue from both datasets
orders_revenue = orders["net_amount_kes"].sum()
items_revenue = order_items["line_net_kes"].sum()

# Compare the results
print("Revenue from orders:", round(orders_revenue, 2))
print("Revenue from order items:", round(items_revenue, 2))
print("Difference:", round(orders_revenue - items_revenue, 2))

Revenue from orders: 253971298.29
Revenue from order items: 253971298.29
Difference: 0.0

### 2.9.4  Before and After Cleaning Summary

In [29]:
print("Missing payment methods:", payment_missing_before, "->", payment_missing_after)
print("Missing age bands:", age_missing_before, "->", age_missing_after)
print("Missing unit prices:", price_missing_before, "->", price_missing_after)
print("Duplicate rows:", duplicates_before, "->", duplicates_after)
print("Quantity outliers:", outliers_before, "->", outliers_after)

Missing payment methods: 791 -> 0
Missing age bands: 152 -> 0
Missing unit prices: 1648 -> 0
Duplicate rows: 989 -> 0
Quantity outliers: 412 -> 0

## 2.10: Saving Cleaned Datasets

In [30]:
# Save cleaned datasets

orders.to_csv("../data/processed/orders.csv", index=False)
order_items.to_csv("../data/processed/order_items.csv", index=False)
customers.to_csv("../data/processed/customers.csv", index=False)
products.to_csv("../data/processed/products.csv", index=False)
stores.to_csv("../data/processed/stores.csv", index=False)
county_population.to_csv("../data/processed/county_population_2019_knbs.csv", index=False)

print("All cleaned datasets saved successfully!")

All cleaned datasets saved successfully!